name: CFLD
channels:
  - pytorch
  - nvidia
  - xformers
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda
  - numpy
  - xformers
  - yacs
  - pandas
  - scikit-image
  - pip:
      - gpustat
      - accelerate
      - tensorboard
      - wandb
      - einops
      - opencv-python
      - timm
      - diffusers
      - safetensors
      - scipy
      - lpips
      - transformers
